---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: gitea
  name: gitea
spec:
  tags:
  - name: "latest"
    from:
      kind: DockerImage
      name: quay.io/atgreen/gitea:latest
    importPolicy: {}
    annotations:
      description: The Gitea git server docker image
      tags: gitea,go,golang
      version: "latest"
