---
apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: gitea
  name: gitea
spec:
  tags:
  - name: "${GITEA_VERSION}"
    from:
      kind: DockerImage
      name: docker.io/atgreen/gitea:latest
    importPolicy: {}
    annotations:
      description: The Gitea git server docker image
      tags: gitea,go,golang
      version: "latest"
