kind: PersistentVolume
apiVersion: v1
metadata:
  name: gitea-data
spec:
  capacity:
    storage: 200Gi
  nfs:
    server: 192.168.1.127
    path: /volume1/ocp.labdroid-pv/pv-labdroid-gitea-data
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: labdroid
    name: gitea-data-claim
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
