---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-postgresql-data-claim
  labels:
    app: gitea
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
