---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  labels:
    app: vault
data:
  vault.hcl: |
    disable_mlock = true
    ui = true
    storage "file" {
      path    = "/opt/vault"
    }
    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_disable = 1
    }
