---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: vault
  name: vault
spec:
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: docker.io/atgreen/labdroid-vault:latest
    importPolicy: {}
    annotations:
      description: A tool for managing secrets
      tags: vault
      version: latest
