---
apiVersion: v1
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vault-data
  labels:
    app: vault
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: "vault-data"
  resources:
    requests:
      storage: 10Gi
