---
apiVersion: route.openshift.io/v1
kind: Route
id: vault-http
metadata:
  annotations:
    description: Route for application's http service.
  labels:
    app: vault
    argocd.argoproj.io/sync-options: Validate=false    
  name: vault
spec:
  host: ""
  to:
    name: vault
