---
apiVersion: route.openshift.io/v1
kind: Route                                  
metadata:                                    
  annotations:                               
    description: Route for application's http
  labels:        
    app: vault   
  name: vault    
spec:
  host: vault-labdroid.apps.ocp.labdroid.net
  to:            
    kind: Service
    name: vault
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
status:
  ingress:
    - conditions:  
