---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  labels:
    app: minio
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: "minio-data"
  resources:
    requests:
      storage: 100Gi
