---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: labdroid-minio-config
  labels:
    app: minio
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: "minio-config"
  resources:
    requests:
      storage: 1Gi
