---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-config-claim
  labels:
    app: minio
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: "minio-config-volume"
  resources:
    requests:
      storage: 1Gi
