---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data-claim
  labels:
    app: minio
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: "minio-data-volume"
  resources:
    requests:
      storage: 100Gi
